baseURL = "https://klempner-liche-de.github.io"
title = "Tella"
author = "p_magyar"
languageCode = "de"
DefaultContentLanguage = "de"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  #mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpg"
    alt = "Steffen Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Klempnerei Liche"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "gallerie"
    name = "Gallerie"
    url = "/gallerie/"
    weight = 1

  [[menu.main]]
    identifier = "projekte"
    name = "Projekte"
    url = "/projekte/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "Über uns"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
